In [3]:
print("Google Colab is working!")




Google Colab is working!


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries imported successfully!")


Libraries imported successfully!


In [9]:

import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)




Array: [10 20 30 40 50]
Shape: (5,)
Data Type: int64


In [10]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Element-wise Multiply:\n", A * B)
print("Matrix Multiplication:\n", A.dot(B))


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiply:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
